### ISSUE TITLE
Stops working after no result

### ISSUE THREAD

**Issue by PalmerAL** [nt1m/InfoCards.js#1]
After an infocard is requested for something nonexistent, the cards stop showing even for cases where there should be a card. Instead, an error is given with "TypeError: Argument 1 of Node.removeChild is not an object." I think the destroy function just needs to check if there is a card before removing it from the container. I'll try to submit a PR for this soon.

**Comment by nt1m** [comment]
Thanks for reporting !
Here's the relevant code : https://github.com/nt1m/InfoCards.js/blob/master/js/infocards.js#L250

**Comment by PalmerAL** [comment]
Actually, why does it need to remove the child anyway? Wouldn't removing all of the inner html do this?

**Comment by nt1m** [comment]
@PalmerAL Good point. I don't really remember why I wrote that line. Maybe there was a reason, but I guess you can remove it.
