### ISSUE TITLE
class for single line answers

### ISSUE THREAD

**Issue by PalmerAL** [nt1m/InfoCards.js#15]
Things that return a single line of text (like calculator, factors, and random name) don't look very good because they are just a regular &lt;p> element. Would it be possible to have something like &lt;p class="answer"> for these so that some styling could be applied to it?

**Comment by nt1m** [comment]
Sure. I'll take care of this tomorrow. The exclusive answers returned by DDG are a bunch of HTML, which makes extracting the answers kinda ugly.

**Comment by nt1m** [comment]
@PalmerAL You can now use .InfoCard-exclusive-answer, applies to _all_ exclusive answers (including color codes). Also added a data-type attribute that has DDG's AnswerType value as value.
