### ISSUE TITLE
Doesn't work when answer is an object

### ISSUE THREAD

**Issue by PalmerAL** [nt1m/InfoCards.js#21]
For example, "Ladder crafting minecraft".

**Comment by nt1m** [comment]
jsonp_callback_69724( {
    "DefinitionSource": "", "Heading": "", "ImageWidth": "", "RelatedTopics": [], "Entity": "", "meta": null, "Type": "E", "Redirect": "", "DefinitionURL": "", "AbstractURL": "", "Definition": "", "AbstractSource": "", "Infobox": "", "Image": "", "ImageIsLogo": "", "Abstract": "", "AbstractText": "", "AnswerType": "minecraft", "ImageHeight": "", "Answer": {
        "name": "Minecraft", "data": {
            "subtitle": "Ingredients: Sticks", "title": "Ladder", "description": "Used for climbing walls. You can climb either horizontally or vertically. To climb safely, you can sneak while climbing (hold shift).", "image": "https://duckduckgo.com/iu/?u=http%3A%2F%2Fwww.minecraftxl.com%2Fimages%2Fwiki%2Frecipes%2Fladder-crafting.png"
        }
        ,
        "meta": {
            "sourceName": "Minecraft Wiki", "sourceUrl": "http://minecraft.gamepedia.com/Crafting#Complete_recipe_list"
        }
        ,
        "from":"minecraft",
        "tab":"answer",
        "id":"minecraft",
        "templates": {
            "group": "info", "options": {
                "moreAt": 1
            }
        }
        ,
        "goodie_with_template":1
    }
    ,
    "Results":[]
}
);

**Comment by nt1m** [comment]
Fixed in https://github.com/nt1m/InfoCards.js/commit/fae059d799a7327045c3211a74a89b39a931e7e7

**Comment by PalmerAL** [comment]
The images for the mincraft example don't work when embedded in another page, so it might be better to leave them out.

**Comment by nt1m** [comment]
@PalmerAL They do for me

**Comment by PalmerAL** [comment]
Weird. They work if I open them in a new tab, but not if they're in the infocard.

**Comment by nt1m** [comment]
@PalmerAL I see the issue in scratchpad, but I have no idea what's going on. The image is served over https, so the protocol shouldn't be a problem

**Comment by PalmerAL** [comment]
I see it in the infocards.js demo page as well. Initially the image doesn't work (I get 403 forbidden), but it works if I copy the URL and open the image in a new tab. Then, the image is cached, so it will appear in the infocards.

I'm guessing that duckduckgo doesn't allow other websites to use its image proxy.
